### ISSUE TITLE
rename CondaScore.read_score -> consume_score

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/language#181]
Since the [read_score](https://github.com/brain-score/core/blob/ea3067b64d3662cfe688ca532ea583a22879634e/brainscore_core/plugin_management/conda_score.py#L42) method deletes the file after reading it, I think it would make sense to signal this destructive operation in the method name. Any concerns about renaming to `consume_score`? (Or a better word if you have ideas)

**Comment by benlipkin** [comment]
seems reasonable to me. can add this to existing [PR:core/33](https://github.com/brain-score/core/pull/33) if everyone's satisfied
