### ISSUE TITLE
GPU accelaration

### ISSUE THREAD

**Issue by rongmu** [brain-score/language#199]
Does benchmarking computation benefit from GPU? Thank you!

Shaoyun

**Comment by mschrimpf** [comment]
It depends on the model and benchmark: for benchmarks with small numbers of stimuli (e.g. Pereira2018), running on GPU does not lead to a speedup in my experience. But for benchmarks with many stimuli (e.g. Futrell2018 or wikitext), running on GPU makes a huge difference, reducing runtime from hours to minutes.

**Comment by rongmu** [comment]
Great to know the speedup for larger benchmarks. Thanks!
