### ISSUE TITLE
variation in context groups across participants not currently supported; relevant for Pereira

### ISSUE THREAD

**Issue by benlipkin** [brain-score/language#79]
While going through the HF model wrapper, I noticed that for a set of stimuli, the context is defined as all preceding text in the benchmark up to and including the text of interest. 

This is correct for Furtrell and Wikitext, where the data is always presented in the same order, but is perhaps misleading for Pereira, where I seem to recall that not all participants saw all the sentences in the same order, but only saw sentences within each passage in the same order. @gretatuckute @aalok-sathe does this seem to be the case as you are looking at this data currently? In that case, the context for any particular sentence would be the preceding text from that passage alone not the whole ordered dataset. 

Under such a case, it might rather make sense to pass text as a doubly-nested list of context groups and stimuli, so that the first loop would isolate the context for a set of stimuli, and the second would then do what’s currently being done in the HF digest text loop. In the case of Wikitext and Furtrell the outer list would just be length 1 and inconsequential, but it would adjust the behavior for Pereira (and support additional use cases where participants saw subsets of a set of stimuli in different orders). 

Thoughts?

@mschrimpf @gretatuckute @aalok-sathe

**Comment by gretatuckute** [comment]
Very much in support of this.

**Comment by mschrimpf** [comment]
I think the best way to implement this is to do the context-looping in the benchmark rather than the model. That is consistent with the current ArtificialSubject specification and should be more readable.

**Comment by benlipkin** [comment]
I agree. Makes more sense for context to be defined by the data packager. Once this has been updated, would you let me know, and I can update the context loop structure for the HF and Container model helper classes.

**Comment by mschrimpf** [comment]
I don't think there will be any changes to the models; all the changes should be on the benchmark side.
